### ISSUE TITLE
restart loop

### ISSUE THREAD

**Issue by masakioui** [ashthespy/Volumio-SpotifyConnect#2]
vollibrespot v0.1.6 cd3b133 2019-04-29 (librespot b5c80bf 2018-11-27) -- Built On 2019-04-29
thread 'main' panicked at 'Invalid bitrate: ()', src/libcore/result.rs:997:5
stack backtrace:
Started Volspotconnect2 Daemon.
0:   0xa0ac27 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hdf951eb9f43ea27e
at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
1:   0xa0669f - std::sys_common::backtrace::_print::h2b5fdbbb5020ccf8
at src/libstd/sys_common/backtrace.rs:70
2:   0xa08cdf - std::panicking::default_hook::{{closure}}::h18d8c59665918d69
at src/libstd/sys_common/backtrace.rs:58
at src/libstd/panicking.rs:200
3:   0xa08947 - std::panicking::default_hook::h1fd1ad969274543a
at src/libstd/panicking.rs:215
4:   0xa0944f - std::panicking::rust_panic_with_hook::h40a77253872948e8
at src/libstd/panicking.rs:478
5:   0xa08fcf - std::panicking::continue_panic_fmt::hec94fc8e5daf641b
at src/libstd/panicking.rs:385
6:   0xa08ebb - rust_begin_unwind
at src/libstd/panicking.rs:312
7:   0xa1bdbb - core::panicking::panic_fmt::h74ee8034b317ceed
at src/libcore/panicking.rs:85
8:   0x524183 - core::result::unwrap_failed::h9bbbc912aacbc69a
9:   0x51deab - vollibrespot::setup::h60afa926408031e2
10:   0x520bf7 - vollibrespot::main::h393279e1f565f771
11:   0x52c407 - std::rt::lang_start::{{closure}}::hb2a63859d18ee1ea
12:   0xa08e33 - std::panicking::try::do_call::h287c6909aadcc5f1
at src/libstd/rt.rs:49
at src/libstd/panicking.rs:297
13:   0xa0da57 - __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:92
14:   0xa098b3 - std::rt::lang_start_internal::h747c58e2c78f4f4f
at src/libstd/panicking.rs:276
at src/libstd/panic.rs:388
at src/libstd/rt.rs:48
15:   0x5214ab - main
16: 0x76cab293 - __libc_start_main
volspotconnect2.service: main process exited, code=exited, status=101/n/a
Unit volspotconnect2.service entered failed state.
Stopping Volspotconnect2 Daemon...

**Comment by ashthespy** [comment]
@masakioui What version are you running? Looks like there was some issues setting up `startconnect.sh` with the right bitrate. Please reinstall the latest version and try. For good measures, after installing, run `killall node` to restart the Volumio process to avoid Volumio caching the old configuration.
