### ISSUE TITLE
volumio invisible on spotify Android app

### ISSUE THREAD

**Issue by RealHayo** [ashthespy/Volumio-SpotifyConnect#3]
I like this plug in very much , but as of since volumio version 2.699 the plug isnt working correctly.
The problem is that with the android app for spotify, the volumio device cannot be chosen anymore since it is not visible in the connect list.
However, and i am not sure if this is related, when running spotify on a webbrowser (open spotify web) it still is possible to see volumio in the connect list. And it still works in that scenario.
When one would then switch back to the spotify android app on ones phone, one can see the volumio device again! But as soon as you stop the music for more than a minute, the android app cannot find volumio anymore.

**Comment by ashthespy** [comment]
Greetings, I hope you have the version from the volumio plugin list, and not from this repo. This one is quite old and hasn't been updated in a while.

For the particular issue of Discovery mode, it is highly dependent on your network conditions, and to ensure that the mdns requests are being broadcast correctly. If you check the logs for the service, there should be some debug messages about incoming requests. Do you see them?

**Comment by RealHayo** [comment]
Hi..
I didnt know where else to turn, with the problem.
I can assure you that I installed the pug in via the user web interface (on volumio.local)
It says it is version 0.9.9 
I have filled in my (paid) account information.
And it works via the open spotify web interface, on a web browser like chrome.
But not on my spotify app on my android (samsung) phone.

I have checked the log via: volumio logdump
But it states no information which you are referring to.
The only error message i see repeated is:
ar 18 16:23 : exception: Failed to open mixer for 'alsa': no such mixer control: PCM

However it does not seem to be a real problem because it plays the music.
(that is music not from spotify but from the NAS)

thank you for response

**Comment by RealHayo** [comment]
Ok, 
maybe this will help...
I got this with sudo journalctl -f
I get this log when I succesfully play music via the open spotify web browser to volumio:

Mar 18 16:32:21 volumio sudo[30246]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 18 16:32:21 volumio sudo[30246]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 18 16:32:21 volumio sudo[30246]: pam_unix(sudo:session): session closed for user root
Mar 18 16:32:21 volumio volumio[758]: info: ------------------------------ 123ms
Mar 18 16:32:21 volumio sudo[30253]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 18 16:32:21 volumio sudo[30253]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 18 16:32:21 volumio sudo[30253]: pam_unix(sudo:session): session closed for user root
Mar 18 16:32:25 volumio volumio[26139]: [Vollibrespot] : SessionActive!
Mar 18 16:32:25 volumio volumio[758]: [SpotifyConnect] Connect Session is active!
Mar 18 16:32:25 volumio volumio[26139]: [Vollibrespot] : Loading <Justify My Love> with Spotify URI <spotify:track:6LvuBSp0sFJgz29h9fjP8s>
Mar 18 16:32:25 volumio volumio[758]: [SpotifyConnect] Pushing metadata Vollibrespot: true
Mar 18 16:32:25 volumio volumio[758]: info: CoreCommandRouter::volumioGetState
Mar 18 16:32:25 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:25 volumio volumio[758]: [SpotifyConnect] Currently active: undefined
Mar 18 16:32:25 volumio volumio[758]: [SpotifyConnect] Pushing new state :: true
Mar 18 16:32:25 volumio volumio[758]: info: CoreCommandRouter::servicePushState
Mar 18 16:32:25 volumio volumio[758]: info: CoreStateMachine::syncState
Mar 18 16:32:25 volumio volumio[758]: info: CoreStateMachine::pushState
Mar 18 16:32:25 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:25 volumio volumio[758]: info: CoreCommandRouter::volumioPushState
Mar 18 16:32:25 volumio volumio[758]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 18 16:32:25 volumio volumio[758]: [SpotifyConnect] Token: <xxxxxxxxxxxxxxxxxxxxx>
Mar 18 16:32:25 volumio kernel: TX ERROR status: 0x007e0000
Mar 18 16:32:25 volumio sudo[30269]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 18 16:32:25 volumio sudo[30269]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 18 16:32:25 volumio sudo[30269]: pam_unix(sudo:session): session closed for user root
Mar 18 16:32:26 volumio volumio[26139]: [Vollibrespot] : <Justify My Love> loaded
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Device is active!
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioGetState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Currently active: volspotconnect2
Mar 18 16:32:26 volumio kernel: snd_pcm_mmap,default
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Vollibrespot Active
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioGetState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Currently active: volspotconnect2
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::servicePushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::syncState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::pushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioPushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioGetState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Currently active: volspotconnect2
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Pushing new state :: true
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::servicePushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::syncState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::pushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioPushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 18 16:32:26 volumio sudo[30279]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 18 16:32:26 volumio sudo[30279]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Sink acquired
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioGetState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Currently active: volspotconnect2
Mar 18 16:32:26 volumio volumio[758]: [SpotifyConnect] Pushing new state :: true
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::servicePushState
Mar 18 16:32:26 volumio sudo[30279]: pam_unix(sudo:session): session closed for user root
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::syncState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::pushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreStateMachine::getState
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::volumioPushState
Mar 18 16:32:26 volumio volumio[758]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 18 16:32:26 volumio sudo[30282]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 18 16:32:26 volumio sudo[30282]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 18 16:32:26 volumio sudo[30282]: pam_unix(sudo:session): session closed for user root
Mar 18 16:32:26 volumio sudo[30294]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 18 16:32:26 volumio sudo[30294]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 18 16:32:26 volumio sudo[30294]: pam_unix(sudo:session): session closed for user root
Mar 18 16:32:27 volumio kernel: TX ERROR status: 0x00760000
Mar 18 16:32:30 volumio kernel: TX ERROR status: 0x007e0000
Mar 18 16:32:30 volumio kernel: TX ERROR status: 0x007e0000

**Comment by RealHayo** [comment]
I have a bad feeling about network config.
Although my devices are on the same network (same router).. 
my volumio device and my computer are both wired to the router, and here the plug in just works fine.
But my android phone is of course WiFi connected to the network (via an AP connected to the router) and in combination with the volumio device (which is still wired), the plug in doesnt work!

It could be coincidence, but we all know ... in computer science there is no coincidence..

your thoughts please...

**Comment by RealHayo** [comment]
again... it is me...
I am so sorry...
As i have experimented with some settings in the android spotify app, i have found a solution.
under settings - devices  
I unchecked the option: Only display local devices

When this is unchecked, volumio is listed again  under the connections in the android app.

**Comment by ashthespy** [comment]
Ah, glad you got it all figured out. 
I see now that you used a logged in directly, and were not using the "discovery" aka multi-use mode, the discovery mode works only on local networks.  

Btw - do you still see the `TX ERROR status: 0x00760000` errors in your log?

**Comment by RealHayo** [comment]
Yes, I still get those errors.
Do not know how or why appear
