### ISSUE TITLE
Incorrect Title for Settings

### ISSUE THREAD

**Issue by billism1** [ashthespy/Volumio-SpotifyConnect#5]
When configuring this plugin, the title is, "Spotify Account". Since the settings really have nothing to do with the user's account, the title should probably be something like, "General Settings".

**Comment by ashthespy** [comment]
Perhaps we can just keep it simple with `Settings`?

**Comment by ashthespy** [comment]
To be very honest, I have no idea how the new system works my self, but I guess we will find out! :-)
