### ISSUE TITLE
Shuffle state on volumio not correct

### ISSUE THREAD

**Issue by dflvunoooooo** [ashthespy/Volumio-SpotifyConnect#7]
When I start plying something via spotify connect and shuffle is on, the icon on volumio does not represent this state. I can change shuffle in spotify via the gui of volumio in spotify connect mode though. This is not a real issue, rather icing on the cake.

**Comment by ashthespy** [comment]
This plugin isn't being maintained by me any longer - it's been integrated into [volumio-plugins-sources](https://github.com/volumio/volumio-plugins-sources/issues) you should open an issue there :-)
